# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_KD_note <- function(X, N_min) {
    .Call(`_FKA_test_KD_note`, X, N_min)
}

