# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_KD_note <- function(X, N_min) {
    .Call(`_mssm_test_KD_note`, X, N_min)
}

naive <- function(X, ws, Y, n_threads) {
    .Call(`_mssm_naive`, X, ws, Y, n_threads)
}

FSKA <- function(X, ws, Y, N_min, eps, n_threads) {
    .Call(`_mssm_FSKA`, X, ws, Y, N_min, eps, n_threads)
}

sample_mv_normal <- function(N, Q, mu) {
    .Call(`_mssm_sample_mv_normal`, N, Q, mu)
}

sample_mv_tdist <- function(N, Q, mu, nu) {
    .Call(`_mssm_sample_mv_tdist`, N, Q, mu, nu)
}

